runtime:
  image: zyeeda/java:latest
  dns:
    - 223.5.5.5
    - 8.8.8.8
  mem_limit: 1000000000
  volumes:
    - ~/.m2/:/root/.m2
    - .:/opt/zyeeda/cdeio-runtime
  working_dir: /opt/zyeeda/cdeio-runtime

